[project]
name = "china-stock-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare>=1.16.26",
    "httpx>=0.28.1",
    "mcp[cli,sse]>=1.3.0",
    "uvicorn[standard]>=0.24.0",
]
